---
- name: Converge
  hosts: all
  tasks:
    - name: "Include ansible-role-update-package-manager-cache"
      ansible.builtin.include_role:
        name: "ansible-role-update-package-manager-cache"
